---
dependencies:
  - name: ui
    version: 1.2.0
    repository: file://../ui

  - name: post
    version: 1.1.3
    repository: file://../post

  - name: comment
    version: 1.1.3
    repository: file://../comment

  - name: mongodb
    version: 0.4.18
    repository: https://kubernetes-charts.storage.googleapis.com
...
